Fix travis

diff --git a/fetch/aix/oratab b/fetch/aix/oratab
--- a/fetch/aix/oratab
+++ b/fetch/aix/oratab
@@ -18,13 +18,13 @@
 ORATAB=$1
 
 if [ -z "$ORATAB" ]; then
-  echo "Missing ORATAB parameter"
+  >&2 echo "Missing ORATAB parameter"
   exit 1
 fi
 
 if [ ! -r "$ORATAB" ]; then
-  echo "The file $ORATAB isn't readable"
-  exit 1
+  >&2 echo "The file $ORATAB isn't readable"
+  exit 0
 fi
 
 sed 's/#.*$//' $ORATAB | grep -v "^$" | grep "^\s*[A-Za-z0-9].*\s*\:" || true
